version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend_app1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_app1
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PORT: ${APP1_PORT}
    ports:
      - "${APP1_PORT}:${APP1_PORT}"
    depends_on:
      - postgres

  backend_app2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_app2
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PORT: ${APP2_PORT}
    ports:
      - "${APP2_PORT}:${APP2_PORT}"
    depends_on:
      - postgres

volumes:
  postgres_data:
