version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend1
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "8001:8001"

  backend2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend2
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "8002:8002"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80" # 외부에서 접근 가능한 Nginx 포트
    volumes:
      - ./nginx.conf:/home/ubuntu/nginx/nginx.conf:ro # Nginx 설정 파일 마운트
    depends_on:
      - backend1
      - backend2

volumes:
  postgres_data:
